import React from 'react'

const TermsOfUse = () => {
  return (
    <main>
        <div className='flex justify-center'>
            <p className='pageTitle mb-5'>3DiF Terms of Use</p>
        </div>
        <div>
            <span className="text-xl text-[#D4B251]">Please Read These Terms of Use Before Accessing Or Using This Website.</span><br/><br/>
            <span className="text-xl font-bold">You Are Bound by These Terms and Conditions</span><br/><br/>
            By accessing this website, you (&quot;User&quot;) accept without limitation or qualification, and agree to be bound and abide by, the following terms and conditions (Terms of Use). 3DiF may revise and update these Terms of Use from time to time using its sole discretion. Your continued use of this website following the posting of revised Terms of Use means that you accept and agree to any and all future changes to the Terms of Use.<br/><br/>
            <span className="text-xl font-bold">User Conduct</span><br/><br/>
            You may use this website only for lawful purposes and in accordance with these Terms of Use, and you agree not to: (i) use this website in any manner that could disable, overburden, damage, or impair this website, or interfere with any other use of this website, including, but not limited to, any user&apos;s ability to engage in real-time activities through this website; (ii) use any robot, spider or other automatic device, process or means to access this website for any purpose, including to monitor or copy any of the material on this website; (iii) use any manual process to monitor or copy any of the material on this website, or to engage in any other unauthorized purpose without the express prior written consent of 3DiF; (iv) otherwise use any device, software or routine that interferes with the proper working of this website; or (v) otherwise attempt to interfere with the proper working of this website.  You further understand and acknowledge that any unauthorized, anti-competitive, or illegal use of the website will be in violation of state and federal law, and you will be subject to criminal and civil penalties as a result.<br/><br/>
            <span className="text-xl font-bold">Disclaimer of warranty; limitation of liability</span><br/><br/>
            (a) user expressly agrees that use of the website and any items or links downloaded or accessed through it is at user&apos;s sole risk. Neither 3DiF, and affiliates nor any of our respective employees, agents, third party content providers or licensors warrant that the website and access to the material contained within it will be uninterrupted or error free; nor do they make any warranty as to the results that may be obtained from use of the website, or as to the accuracy, reliability or content of any information or service provided through the website. 3DiF  has not reviewed all the sites linked to the website and is not responsible for the contents of any off-site pages or any other sites linked to the website.
            (b) 3DiF&apos;s website is provided on an &quot;as is&quot; basis without warranties of any kind, either express or implied, including, but not limited to, warranties of title or implied warranties of merchantability or fitness for a particular purpose, other than those warranties which are implied by and incapable of exclusion, restriction, or modification under the laws applicable to this agreement. 3DiF makes no representation that materials on the website are legally accessible from any location and access to them from territories where their contents are illegal is prohibited.
            (c) Under no circumstances shall 3DiF or any person or entity involved in creating, producing or distributing 3DiF&apos;s website content be liable for any direct, indirect, special, incidental or consequential damages, including, but not limited to loss of data or profit, arising out of the use, or the inability to use, the materials on the website, even if 3DiF or a 3DiF authorized representative has been advised of the possibility of such damages. 3DiF also assumes no responsibility, and shall not be liable for, any damages to, or viruses that may infect, computer equipment or other property on account of access to, use of, or browsing in the website or downloading of any materials, data, text, images, video, or audio from the website. This disclaimer of liability applies to any damages or injury caused by any failure of performance, error, omission, interruption, deletion, defect, delay in operation or transmission, computer virus, communication line failure, theft or destruction or unauthorized access to, alteration of, or use of the website, whether for breach of contract, indigenous  behavior, negligence, or under any other cause of action. User specifically acknowledges that 3DiF is not liable for the defamatory, offensive or illegal conduct of third parties and that the risk of injury from the foregoing rests entirely with user. User hereby acknowledges that the provisions of this section shall apply to all pages on 3DiF&apos;s  website.<br/><br/>
            <span className="text-xl font-bold">Miscellaneous</span><br/><br/>
            (A) The copyright all material provided on the website is held by 3DiF, its employees, and affiliates, or provided with permission from the copyright owner.
            (B) The trademarks, service marks, photos, and logos (the &quot;Trademarks&quot;) used and displayed on this Site are registered and unregistered Trademarks of 3DiF and others. Nothing on this Site should be construed as granting, by implication, estoppel, or otherwise, any license or right to use any Trademark displayed on the Site, without the written permission of the Trademark owner. The name &quot;3DiF&quot; and its logos may not be used in any way, including in advertising or publicity pertaining to distribution of materials on this Site without prior, written permission from 3DiF. 3DiF prohibits use of the 3DiF logo and Employee&apos;s information as a &quot;hot&quot; link to any 3DiF site unless establishment of such a link is approved in advance 3DiF in writing.<br/><br/>
            <span className="text-xl font-bold">Indemnification</span><br/><br/>
            User agrees to defend, indemnify, and hold harmless 3DiF, its employees and affiliates and their respective directors, officers, employees and agents from and against all claims and expenses, including attorneys&apos; fees, arising out of the unauthorized use of 3DiF&apos;s website by or on behalf of the User.
            <p></p>
        </div>
    </main>
  )
}

export default TermsOfUse